<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\Common.props" />

  <ItemGroup>
    <PackageReference Include="Miyabi.Asset.Models" Version="3.4.0" />
    <PackageReference Include="Miyabi.Contract.Client" Version="3.4.0" />
    <PackageReference Include="Miyabi.ContractSdk" Version="3.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Utility\Utility.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="ContractFiles\SampleContract.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

</Project>
