<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\Common.props" />

  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Miyabi.ClientSdk" Version="3.5.0" />
    <PackageReference Include="Miyabi.Cryptography.Secp256k1" Version="3.5.0" />
    <PackageReference Include="Miyabi.Hash.NativeHash" Version="3.5.0" />
    <PackageReference Include="Miyabi.ModelSdk" Version="3.5.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
