<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\Common.props" />

  <ItemGroup>
    <PackageReference Include="Miyabi.Asset.Client" Version="3.5.0" />
    <PackageReference Include="Miyabi.Asset.Models" Version="3.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Utility\Utility.csproj" />
  </ItemGroup>

</Project>
